### ISSUE TITLE
Attempt to call defined symbol results in segmentation fault.

### ISSUE THREAD

**Issue by wired-lain** [sovietspaceship/lolisp#3]
To reproduce:

λ) (define a 1)
Object at 0:()
address: 0x6dba90
type: ATOM
trait: INT
value: 1
tail: 0x6dbb20
1 NIL 

λ) (a)
zsh: segmentation fault (core dumped)  ./lolisp

Probably a result of not flagging certain objects as callable?

**Comment by sovietspaceship** [comment]
Every object is callable in principle, but the call() at the moment expects a list. I'll fix this

**Comment by sovietspaceship** [comment]
Fixed
